--BASE DE DATOS PARA DESARROLLO DE SISTEMAS I
CREATE DATABASE COMPUTADORA_DB


CREATE TABLE COMPUTADORA (
ID INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
DESCRIPCION NVARCHAR (50) NOT NULL,
PRECIO MONEY NULL,
FECHAFABRIC DATETIME NOT NULL,
PRIMARY KEY (ID),
);
